### ISSUE TITLE
Como usuario quiero un menú de acción

### ISSUE THREAD

**Issue by nataliaaberghina** [candelapamelin/BIBLIOTECA#1]
Buscar y solicitar libros:* - Explorar el catálogo en línea para encontrar libros, revistas u otros recursos. - Solicitar libros específicos para préstamo o consulta. 2. **Préstamo y devolución:* - Prestar libros para llevar a casa por un período determinado. - Devolver los materiales prestados en la fecha acordada. 3. *Asistencia y orientación:* - Obtener ayuda para encontrar recursos específicos o realizar investigaciones. - Solicitar recomendaciones de lectura o información sobre temas particulares. 4. *Acceso a recursos en línea:* - Utilizar computadoras o acceder a la red Wi-Fi para acceder a bases de datos, libros electrónicos o recursos en línea. 5. *Participar en eventos y programas:* - Asistir a charlas, talleres o clubes de lectura organizados por la biblioteca. 6. *Estudio y lectura en la biblioteca:*

**Comment by candelapamelin** [comment]
1. **Búsqueda de materiales:** - Acceso al catálogo en línea para buscar libros, revistas, películas u otros recursos disponibles en la biblioteca. 
2. **Préstamo de materiales:** - Solicitar préstamo de libros u otros materiales para llevar a casa por un período determinado. 
3. **Devolución de materiales:** - Devolver los materiales prestados en la fecha indicada. 
4. **Asistencia y orientación:** - Obtener ayuda de los bibliotecarios para encontrar información, sugerencias de lectura o recursos específicos. 
5. **Uso de recursos digitales:** - Acceder a computadoras, internet o recursos digitales disponibles en la biblioteca.
6. **Participación en eventos y programas:** - Registrarse para eventos, talleres, charlas o clubes de lectura organizados por la biblioteca.
